# Generated by Django 5.0.14 on 2026-07-16 16:39

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('_bank_account_details', models.TextField(db_column='bank_account_details')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
